title:  Rudin's Home
author: Rudin
email:  your-email@domain.com
description: >-
    A personal blog for taking notes and sharing knowledge
baseurl:    "/rudin"
url:        ""

social_link:
    github: "github.com/example-user"

permalink: "/post/:title/"

# Build Setting
plugins:
    - jekyll-paginate


# paginate setting
paginate: 5
paginate_path: "/page/:num"

# deployment setting
host: 0.0.0.0
port: 4000
